# Generated by Django 4.2.16 on 2026-06-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='category',
            name='keywords',
        ),
    ]
